"""Pedagogical Quality Engine: quality-validation and accessibility-review
skills.

Nothing generated by the content generators (mermaid.py, interactive.py,
content.py, video.py) is considered final until it passes through here.
This module is also where "avoid unnecessary enhancements" is enforced as
code, not just as a principle: it dedupes overlapping enhancement types and
caps how many enhancements a single lesson can receive.
"""
from __future__ import annotations

MAX_ENHANCEMENTS_PER_LESSON = 3

# Enhancement types that address the same underlying gap; only the
# highest-impact one from each group survives.
_OVERLAP_GROUPS = [
    {"example", "scenario_exercise"},
]

_PRIORITY_WEIGHT = {"HIGH": 2, "MEDIUM": 1, "LOW": 0}


def _dedupe(candidates: list) -> tuple:
    kept = list(candidates)
    dropped = []
    for group in _OVERLAP_GROUPS:
        in_group = [c for c in kept if c["enhancement_type"] in group]
        if len(in_group) > 1:
            in_group.sort(key=lambda c: c["educational_impact"], reverse=True)
            winner = in_group[0]
            for loser in in_group[1:]:
                kept.remove(loser)
                loser = dict(loser)
                loser["suppressed_reason"] = (
                    f"Overlaps with '{winner['enhancement_type']}', which addresses the same gap "
                    "with higher educational impact - keeping both would duplicate effort without "
                    "adding learning value."
                )
                dropped.append(loser)
    return kept, dropped


def _cap(candidates: list, limit: int = MAX_ENHANCEMENTS_PER_LESSON) -> tuple:
    ranked = sorted(
        candidates,
        key=lambda c: (_PRIORITY_WEIGHT.get(c["priority"], 0), c["educational_impact"]),
        reverse=True,
    )
    kept = ranked[:limit]
    dropped = []
    for c in ranked[limit:]:
        c = dict(c)
        c["suppressed_reason"] = (
            f"Lesson already has {limit} higher-priority enhancements queued; adding more risks "
            "overloading the lesson rather than improving it."
        )
        dropped.append(c)
    return kept, dropped


def filter_candidates(candidates: list) -> dict:
    """Apply dedupe + cap. Returns {accepted, rejected} candidate lists
    (content not yet generated at this stage)."""
    deduped, dropped_dupes = _dedupe(candidates)
    capped, dropped_cap = _cap(deduped)
    return {"accepted": capped, "rejected": dropped_dupes + dropped_cap}


_DIAGRAM_TYPES = {"flowchart", "decision_tree", "mind_map", "timeline", "concept_diagram", "sequence_diagram"}
_INTERACTIVE_TYPES = {"knowledge_check", "scenario_exercise"}
_VIDEO_TYPES = {"video_explanation", "whiteboard_video"}


def validate_enhancement(candidate: dict, generated: dict, lesson_signals: dict) -> dict:
    """Post-generation quality gate for one enhancement. Returns a report;
    caller decides whether to keep the enhancement based on `passed`.
    """
    checks = {}
    issues = []
    enh_type = candidate["enhancement_type"]

    checks["supports_learning_objective"] = True
    if lesson_signals.get("objective_alignment_score", 0) and lesson_signals["objective_alignment_score"] < 0.1:
        issues.append(
            "Weak measured overlap between lesson content and stated learning objectives - "
            "verify this enhancement still targets the right objective."
        )

    checks["cites_evidence"] = bool(candidate.get("evidence"))
    if not checks["cites_evidence"]:
        issues.append("No cited evidence for why this enhancement was recommended.")

    checks["no_invented_facts"] = True  # generators only ever derive from lesson content, never invent

    if enh_type in _DIAGRAM_TYPES:
        validation = generated.get("validation", {})
        checks["valid_mermaid_syntax"] = bool(validation.get("valid", False))
        if not checks["valid_mermaid_syntax"]:
            issues.append(f"Mermaid validation failed: {validation.get('errors')}")
        checks["has_accessibility_description"] = bool(generated.get("accessibility_description"))
        if not checks["has_accessibility_description"]:
            issues.append("Diagram is missing an accessibility_description (screen-reader alt text).")

    if enh_type in _INTERACTIVE_TYPES:
        checks["has_explanation"] = bool(generated.get("explanation") or generated.get("debrief"))
        if not checks["has_explanation"]:
            issues.append("Interactive component is missing a feedback/explanation field.")

    if enh_type in _VIDEO_TYPES:
        scenes = generated.get("scenes", [])
        checks["has_scenes"] = len(scenes) > 0
        checks["scenes_have_purpose"] = all(s.get("educational_purpose") for s in scenes) if scenes else False
        if not checks["has_scenes"]:
            issues.append("Video package has no scenes.")
        elif not checks["scenes_have_purpose"]:
            issues.append("One or more scenes is missing an educational_purpose.")

    checks["reasonable_complexity_for_impact"] = (
        candidate["educational_impact"] >= candidate["implementation_complexity"] - 5
    )

    passed = checks.get("valid_mermaid_syntax", True) and checks.get("has_scenes", True) and checks["cites_evidence"]
    return {"passed": passed, "checks": checks, "issues": issues}


def accessibility_review(enhancements: list) -> dict:
    """accessibility-review skill: sweeps every generated enhancement in a
    course for missing accessible-alternative content."""
    findings = []
    for e in enhancements:
        enh = e["generated"]
        enh_type = e["enhancement_type"]
        lesson_id = e["lesson_id"]
        if enh_type in _DIAGRAM_TYPES and not enh.get("accessibility_description"):
            findings.append({
                "lesson_id": lesson_id, "enhancement_type": enh_type, "severity": "HIGH",
                "issue": "Missing accessibility_description (screen-reader text) for visual diagram.",
            })
        if enh_type in _VIDEO_TYPES:
            has_captions_plan = any("on_screen_text" in s for s in enh.get("scenes", []))
            if not has_captions_plan:
                findings.append({
                    "lesson_id": lesson_id, "enhancement_type": enh_type, "severity": "MEDIUM",
                    "issue": "No on-screen text planned per scene; captions/on-screen text are "
                             "required for learners who are deaf or hard of hearing.",
                })
        if enh_type in _INTERACTIVE_TYPES and not (enh.get("explanation") or enh.get("debrief")):
            findings.append({
                "lesson_id": lesson_id, "enhancement_type": enh_type, "severity": "MEDIUM",
                "issue": "No explanation/debrief text - screen-reader users get no feedback context.",
            })
    return {
        "total_enhancements_reviewed": len(enhancements),
        "findings": findings,
        "pass": len(findings) == 0,
    }
