"""LMS Capability Requirements Engine + Odoo Requirements Generator +
Module Dependency Graph.

This is the boundary layer described in the master spec: it inspects the
enhancements this specific course actually received (never the full set of
everything the engine *could* generate) and reports (a) generic LMS
capabilities required, classified as existing-Odoo / existing-custom /
recommended-new-module / external-service, and (b) concrete recommended
Odoo module specifications an Odoo developer can implement from. The engine
never claims a module already exists - every module here is explicitly
labeled "Recommended Custom Odoo Module".
"""
from __future__ import annotations

# enhancement_type -> technical module name (None = no rendering capability needed)
ENHANCEMENT_TO_MODULE = {
    "flowchart": "course_enhancer_mermaid",
    "decision_tree": "course_enhancer_mermaid",
    "concept_diagram": "course_enhancer_mermaid",
    "sequence_diagram": "course_enhancer_mermaid",
    "timeline": "course_enhancer_timeline",
    "mind_map": "course_enhancer_mindmap",
    "comparison_table": "course_enhancer_comparison",
    "knowledge_check": "course_enhancer_quiz",
    "scenario_exercise": "course_enhancer_quiz",
    "summary_and_key_takeaways": "course_enhancer_content_blocks",
    "example": "course_enhancer_content_blocks",
    "case_study": "course_enhancer_content_blocks",
    "video_explanation": "course_enhancer_video",
    "whiteboard_video": "course_enhancer_video",
    "voiceover": "course_enhancer_audio",
    "structural_recommendation": None,
}

MODULE_CATALOG = {
    "course_enhancer_core": {
        "module_name": "Course Enhancer Core",
        "purpose": (
            "Base framework module: data model linking a lesson/content record to its generated "
            "enhancements, security groups, and the admin menu every other course_enhancer_* "
            "module attaches to."
        ),
        "required_features": [
            "Generic 'enhancement' model (type, priority, JSON payload, source lesson reference)",
            "Security groups for course authors vs. learners",
            "Top-level admin menu for reviewing generated enhancements before publishing",
        ],
        "input_data": {"enhancement_package": "enhancement-package.json (see requirements/)"},
        "output_behavior": "Provides the data model and menu other course_enhancer_* modules build on; no learner-facing UI of its own.",
        "api_requirements": ["Import endpoint accepting enhancement-package.json"],
        "dependencies": [],
        "capability": "Base Extension Framework / Data Model",
    },
    "course_enhancer_assets": {
        "module_name": "Course Enhancer Asset Storage",
        "purpose": "Stores and attaches generated enhancement assets (diagram source, tables, video/audio references) to their lesson record.",
        "required_features": [
            "Attachment model linked to core enhancement records",
            "Versioning so a re-generated enhancement doesn't silently overwrite the prior one",
        ],
        "input_data": {"assets": "enhancement-package.json .assets / .video_packages / .voiceover_packages"},
        "output_behavior": "Makes generated assets retrievable by the rendering modules below.",
        "api_requirements": ["CRUD endpoints for asset records"],
        "dependencies": ["course_enhancer_core"],
        "capability": "Generic Asset Storage & Attachment",
    },
    "course_enhancer_mermaid": {
        "module_name": "Mermaid Diagram Renderer",
        "purpose": "Render Mermaid diagrams (flowchart, decision tree, concept diagram, sequence diagram) generated by the engine inside course lessons.",
        "required_features": [
            "Accept Mermaid source code", "Validate Mermaid syntax before render",
            "Render diagrams safely (sandboxed client-side render or server-side SVG)",
            "Responsive layout", "Display the generated accessibility_description as alt text",
        ],
        "input_data": {"diagram_type": "flowchart|decision_tree|...", "mermaid_code": "string", "title": "string", "accessibility_description": "string"},
        "output_behavior": "Rendered interactive/static diagram inside the lesson.",
        "api_requirements": ["POST /diagram/render (or client-side Mermaid.js bundle)"],
        "dependencies": ["course_enhancer_core"],
        "capability": "Diagram Rendering (Mermaid-compatible)",
    },
    "course_enhancer_mindmap": {
        "module_name": "Mind Map Renderer",
        "purpose": "Render mind-map diagrams generated by the engine; may reuse the Mermaid renderer's `mindmap` diagram type under a distinct module boundary for LMS teams that license/theme mind maps separately.",
        "required_features": ["Accept Mermaid `mindmap` source", "Render as an explorable/collapsible tree", "Responsive layout"],
        "input_data": {"mermaid_code": "string", "nodes": "array"},
        "output_behavior": "Rendered mind map inside the lesson.",
        "api_requirements": ["Shares the render pipeline exposed by course_enhancer_mermaid"],
        "dependencies": ["course_enhancer_core", "course_enhancer_mermaid"],
        "capability": "Mind Map Rendering",
    },
    "course_enhancer_timeline": {
        "module_name": "Timeline Renderer",
        "purpose": "Render chronological/staged-progression timelines generated by the engine.",
        "required_features": ["Accept Mermaid `timeline` source", "Render as a horizontal or vertical timeline", "Responsive layout"],
        "input_data": {"mermaid_code": "string", "nodes": "array"},
        "output_behavior": "Rendered timeline inside the lesson.",
        "api_requirements": ["Shares the render pipeline exposed by course_enhancer_mermaid"],
        "dependencies": ["course_enhancer_core", "course_enhancer_mermaid"],
        "capability": "Timeline Rendering",
    },
    "course_enhancer_comparison": {
        "module_name": "Comparison Table Renderer",
        "purpose": "Render structured comparison tables generated by the engine as responsive, scannable tables.",
        "required_features": ["Accept {items, criteria, supporting_text_per_criterion}", "Responsive table layout (horizontal scroll on mobile)"],
        "input_data": {"items": "array", "criteria": "array", "markdown_table": "string"},
        "output_behavior": "Rendered comparison table inside the lesson.",
        "api_requirements": ["No external API required; server-side template render"],
        "dependencies": ["course_enhancer_core"],
        "capability": "Comparison Table Rendering",
    },
    "course_enhancer_interactive": {
        "module_name": "Interactive Component Framework",
        "purpose": "Base framework for rendering any interactive component, capturing learner responses, and tracking attempts/completion.",
        "required_features": ["Response capture model", "Attempt/completion tracking", "Grading hook for MC/TF/matching"],
        "input_data": {"interaction_type": "multiple_choice|true_false|matching|scenario_question"},
        "output_behavior": "Provides the learner-response data model course_enhancer_quiz renders against.",
        "api_requirements": ["POST /interaction/submit"],
        "dependencies": ["course_enhancer_core"],
        "capability": "Interactive Component Framework",
    },
    "course_enhancer_quiz": {
        "module_name": "Interactive Assessment Renderer",
        "purpose": "Render knowledge-check and scenario interactive components generated by the engine (multiple choice, true/false, matching, scenario question), capture responses, and show the generated explanation/debrief.",
        "required_features": ["Render each interaction type", "Immediate feedback using the generated `explanation` field", "Score/attempt tracking"],
        "input_data": {"type": "multiple_choice|true_false|matching|scenario_question", "question": "string", "options": "array", "correct_answer": "string", "explanation": "string"},
        "output_behavior": "Learner-facing interactive assessment with feedback.",
        "api_requirements": ["POST /interaction/submit", "GET /interaction/{id}/results"],
        "dependencies": ["course_enhancer_core", "course_enhancer_interactive"],
        "capability": "Interactive Assessment Engine",
    },
    "course_enhancer_content_blocks": {
        "module_name": "Custom Content Block Renderer",
        "purpose": "Render generated summary/key-takeaway, worked-example, and case-study blocks inside a lesson without a full page-builder edit.",
        "required_features": ["Render summary + key_takeaways list", "Render example/case-study scaffold with clear 'needs author review' styling for unfilled placeholders"],
        "input_data": {"summary": "string", "key_takeaways": "array", "example_scaffold": "string"},
        "output_behavior": "Rendered content block inside the lesson.",
        "api_requirements": ["No external API required; server-side template render"],
        "dependencies": ["course_enhancer_core"],
        "capability": "Custom Content Blocks",
    },
    "course_enhancer_video": {
        "module_name": "Video Asset Manager & Player",
        "purpose": "Store, manage, and play video assets whose scripts/storyboards were generated by the engine's video_explanation/whiteboard_video packages, once those packages have been rendered into actual video files by a separate production step.",
        "required_features": ["Video asset storage/CDN reference", "Player with caption/on-screen-text track support", "Link back to the source video_explanation package for QA"],
        "input_data": {"video_package": "video_explanation or whiteboard_video JSON package", "rendered_video_url": "string (populated by the separate rendering step)"},
        "output_behavior": "Playable video embedded in the lesson once rendered footage is uploaded.",
        "api_requirements": ["POST /video/upload", "GET /video/{id}"],
        "dependencies": ["course_enhancer_core", "course_enhancer_assets"],
        "capability": "Video Asset Management & Playback",
    },
    "course_enhancer_audio": {
        "module_name": "Voiceover Audio Manager",
        "purpose": "Store and play voiceover audio assets referenced by generated voiceover packages, synced to video scene timing, once audio has been synthesized/recorded by a separate step.",
        "required_features": ["Audio asset storage keyed by lesson_id/scene_number", "Sync metadata (duration per scene) for player alignment"],
        "input_data": {"voiceover_package": "voiceover JSON package", "asset_path": "string naming convention: assets/voiceovers/<lesson_id>/scene_NN.mp3"},
        "output_behavior": "Audio track available to course_enhancer_video's player.",
        "api_requirements": ["POST /audio/upload", "GET /audio/{id}"],
        "dependencies": ["course_enhancer_core", "course_enhancer_assets", "course_enhancer_video"],
        "capability": "Audio/Voiceover Asset Management",
    },
    "course_enhancer_analytics": {
        "module_name": "Enhancement Engagement Analytics",
        "purpose": "Track learner interaction with generated enhancements (diagram views, quiz attempts/scores, video watch completion) to feed back into future course quality decisions.",
        "required_features": ["Event logging per enhancement type", "Aggregate dashboard per lesson/module"],
        "input_data": {"event": "{enhancement_id, learner_id, event_type, timestamp}"},
        "output_behavior": "Aggregate engagement/quality dashboards.",
        "api_requirements": ["POST /analytics/event"],
        "dependencies": ["course_enhancer_core"],
        "capability": "Enhancement Engagement Analytics",
    },
}

# Default implementation phase per module, mirroring the spec's own
# PHASE 1/2/3 example groupings.
DEFAULT_PHASE = {
    "course_enhancer_core": 1,
    "course_enhancer_assets": 1,
    "course_enhancer_mermaid": 1,
    "course_enhancer_mindmap": 1,
    "course_enhancer_timeline": 1,
    "course_enhancer_comparison": 1,
    "course_enhancer_interactive": 2,
    "course_enhancer_quiz": 2,
    "course_enhancer_content_blocks": 2,
    "course_enhancer_video": 3,
    "course_enhancer_audio": 3,
    "course_enhancer_analytics": 3,
}
PHASE_PRIORITY = {1: "HIGH", 2: "MEDIUM", 3: "LOW"}

# A's/B's/C's/D's per the spec's classification requirement. Nothing here is
# ever asserted to already exist - see classification_note on each.
_CLASSIFICATION = {
    "course_enhancer_core": ("C", "New custom module; Odoo has no equivalent 'course enhancement' data model out of the box."),
    "course_enhancer_assets": ("B", "May partially overlap with Odoo's native ir.attachment; recommend building on top of it rather than duplicating storage."),
    "course_enhancer_content_blocks": ("B", "May partially overlap with Odoo's website/page-builder snippets; verify whether a custom snippet is sufficient before building a full module."),
}


def _classification_for(technical_name: str):
    return _CLASSIFICATION.get(technical_name, ("C", "Recommended new custom module; no existing Odoo capability covers this."))


def required_modules_for(enhancement_package: dict) -> set:
    """Only modules this specific course's ACTUAL enhancements need - never
    the full catalog. Includes transitive dependencies."""
    types_present = {e["enhancement_type"] for e in enhancement_package["enhancements"]}
    direct = {ENHANCEMENT_TO_MODULE[t] for t in types_present if ENHANCEMENT_TO_MODULE.get(t)}
    if enhancement_package.get("video_packages") or enhancement_package.get("whiteboard_video_packages"):
        direct.add("course_enhancer_video")
    if enhancement_package.get("voiceover_packages"):
        direct.add("course_enhancer_audio")

    if not direct:
        return set()

    required = set(direct)
    required.add("course_enhancer_core")
    required.add("course_enhancer_assets")

    changed = True
    while changed:
        changed = False
        for name in list(required):
            for dep in MODULE_CATALOG.get(name, {}).get("dependencies", []):
                if dep not in required:
                    required.add(dep)
                    changed = True

    has_interactive_or_video = bool(
        {"course_enhancer_quiz", "course_enhancer_video"} & required
    )
    if has_interactive_or_video:
        required.add("course_enhancer_analytics")

    return required


def build_lms_capabilities(enhancement_package: dict) -> dict:
    """Generic, LMS-agnostic capability report (skill: none directly, but
    this is the 'LMS Capability Requirements Engine' deliverable)."""
    required = required_modules_for(enhancement_package)
    types_present = {}
    for e in enhancement_package["enhancements"]:
        types_present.setdefault(ENHANCEMENT_TO_MODULE.get(e["enhancement_type"]), []).append(e["enhancement_type"])

    capabilities = []
    for name in sorted(required):
        spec = MODULE_CATALOG[name]
        classification, note = _classification_for(name)
        capabilities.append({
            "capability": spec["capability"],
            "technical_module_name": name,
            "required_by_enhancement_types": sorted(set(types_present.get(name, []))),
            "classification": {
                "A_existing_odoo_capability": classification == "A",
                "B_existing_custom_capability": classification == "B",
                "C_recommended_new_custom_module": classification == "C",
                "D_external_service_integration": classification == "D",
            },
            "classification_note": note,
        })
    return {
        "course_id": enhancement_package["course_id"],
        "required_capabilities": capabilities,
        "note": (
            "This list reflects only the capabilities this course's actual generated "
            "enhancements require - not the full set of capabilities the engine is able to "
            "produce. Do not install modules for capabilities with zero required_by entries."
        ),
    }


def build_odoo_requirements(enhancement_package: dict) -> dict:
    required = required_modules_for(enhancement_package)
    types_present = {}
    for e in enhancement_package["enhancements"]:
        types_present.setdefault(ENHANCEMENT_TO_MODULE.get(e["enhancement_type"]), []).append(e["enhancement_type"])

    modules = []
    for name in sorted(required):
        spec = MODULE_CATALOG[name]
        phase = DEFAULT_PHASE[name]
        classification, note = _classification_for(name)
        modules.append({
            "module_name": spec["module_name"],
            "technical_name": name,
            "type": "Recommended Custom Odoo Module",
            "purpose": spec["purpose"],
            "required_features": spec["required_features"],
            "input_data": spec["input_data"],
            "output_behavior": spec["output_behavior"],
            "api_requirements": spec["api_requirements"],
            "dependencies": spec["dependencies"],
            "priority": PHASE_PRIORITY[phase],
            "phase": phase,
            "required_by_course_features": sorted(set(types_present.get(name, []))) or ["(transitive dependency only)"],
            "classification": classification,
            "classification_note": note,
        })

    phases = {
        "phase_1_required": sorted(m["technical_name"] for m in modules if m["phase"] == 1),
        "phase_2_important": sorted(m["technical_name"] for m in modules if m["phase"] == 2),
        "phase_3_optional": sorted(m["technical_name"] for m in modules if m["phase"] == 3),
    }

    return {
        "course_id": enhancement_package["course_id"],
        "modules": modules,
        "phases": phases,
        "note": (
            "Every module below is a PROPOSED custom Odoo module - none of these are assumed to "
            "already exist. Odoo deployment, self-hosting, custom module development, database "
            "implementation, UI rendering, API endpoints, and uploading these packages into Odoo "
            "are the responsibility of a separate Odoo developer/team."
        ),
    }


def build_module_dependency_graph(odoo_requirements: dict) -> dict:
    edges = []
    for module in odoo_requirements["modules"]:
        for dep in module["dependencies"]:
            edges.append({"from": dep, "to": module["technical_name"]})
    nodes = [{"technical_name": m["technical_name"], "phase": m["phase"]} for m in odoo_requirements["modules"]]
    return {"course_id": odoo_requirements["course_id"], "nodes": nodes, "edges": edges}
